# render.yaml
# Defines the database and backend web service

databases:
  - name: citypulse-db
    plan: free

services:
  - type: web
    name: Citypulse-360-BackEnd
    plan: free
    env: python
    pythonVersion: "3.11.9"
    
    # Run commands from the BackEnd folder
    rootDir: BackEnd
    
    # Build and Start commands
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn BackEnd.services.main:app"
    
    # Environment variables
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: citypulse-db
          property: internalUrl
      # For security, add your other API keys (OWM_KEY, etc.)
      # directly in the Render dashboard's Environment tab after deploying.